[tool.ruff]
select = ["E", "F", "I"]
ignore = []
line-length = 120
exclude = ["tests", "scripts"]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests that require a live device",
]
